branch-defaults:
  master:
    environment: MyDummyApp-env-latest
environment-defaults:
  MyDummyApp-env-latest:
    branch: master
    repository: https://github.com/NengKK/my-dummy-app
global:
  application_name: my-dummy-app
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ap-southeast-1::platform/Node.js running
    on 64bit Amazon Linux/4.11.0
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
