version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:10.16.0-browsers
    steps:
      - checkout
      - run:
          name: Install
          command: |
            npm install
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - test-branch-changing