version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:10.16.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Check unix release
          command: lsb_release -a
      - run:
          name: Check shell's profile
          command: ls -a ~
      - run:
          name: Check python version
          command: python --version
      - run:
          name: Install PIP
          command: sudo apt install python-pip
      - run:
          name: Install awscli
          command: |
            sudo pip install awsebcli --upgrade --user
      - run:
          name: Add executable path
          command: export PATH=~/.local/bin:$PATH
      - run:
          name: Create AWS credentials manually
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[profile eb-cli]" > ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run:
          name: Set environment variables
          command: |
            eb setenv CIRCLE_CI_TOKEN=${CIRCLE_CI_TOKEN} GITHUB_USER=${GITHUB_USER} PROJECT_NAME=${PROJECT_NAME}
      - run:
          name: Deploy to EB
          command: |
            eb use MyDummyApp-env-latest --profile eb-cli
            eb deploy -v --staged --profile eb-cli
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
                - test-circlr-ci